

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: lavina-trucking-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lavina_trucking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lavina-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lavina-trucking-backend
    restart: unless-stopped
    environment:
      APP_NAME: "Lavina Trucking"
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://localhost:8000
      
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: lavina_trucking
      DB_USERNAME: root
      DB_PASSWORD: root
      
      LOG_CHANNEL: stack
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
    ports:
      - "8000:80"
    volumes:
      - ./backend/storage:/var/www/html/storage
    depends_on:
      database:
        condition: service_healthy
    networks:
      - lavina-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lavina-trucking-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - lavina-network

  # phpMyAdmin (optional, for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lavina-trucking-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - lavina-network

volumes:
  mysql_data:
    driver: local

networks:
  lavina-network:
    driver: bridge
