import type { ScheduleType, Driver } from "@/types/type";

export const MockData: ScheduleType[] = [
  {
    id: "98HJDADH",
    date: "2025-08-15",
    time: "08:30 AM",
    locations: {
      departure_point: "Matina Crossing, Davao City",
      destination: "Bangkal, Davao City",
    },
    goods: {
      item: "Sand",
      weight_in_kgs: "200",
    },
    truck_number: "LHE 1234",
  },
  {
    id: "75ASIUFSD",
    date: "2025-08-20",
    time: "2:00 PM",
    locations: {
      departure_point: "Matina Aplaya, Davao City",
      destination: "Bangkal, Davao City",
    },
    goods: {
      item: "Metal",
      weight_in_kgs: "400",
    },
    truck_number: "YGV 4128",
  },
  {
    id: "12HBDAJI",
    date: "2025-08-25",
    time: "09:15 AM",
    locations: {
      departure_point: "Matina Aplaya, Davao City",
      destination: "Bangkal, Davao City",
    },
    goods: {
      item: "Gravel",
      weight_in_kgs: "100",
    },
    truck_number: "LHE 1234",
  },
  {
    id: "45KDMSNF",
    date: "2025-08-05",
    time: "07:00 AM",
    locations: {
      departure_point: "Puan, Davao City",
      destination: "Toril, Davao City",
    },
    goods: {
      item: "Concrete Blocks",
      weight_in_kgs: "500",
    },
    truck_number: "DVO 2468",
  },
  {
    id: "89PLMQRT",
    date: "2025-08-12",
    time: "01:30 PM",
    locations: {
      departure_point: "Ulas, Davao City",
      destination: "Matina, Davao City",
    },
    goods: {
      item: "Construction Steel",
      weight_in_kgs: "350",
    },
    truck_number: "DVR 9753",
  },
  {
    id: "23VBNMKL",
    date: "2025-08-18",
    time: "10:45 AM",
    locations: {
      departure_point: "Bangkal, Davao City",
      destination: "Puan, Davao City",
    },
    goods: {
      item: "Crushed Stone",
      weight_in_kgs: "300",
    },
    truck_number: "LHE 1234",
  },
  {
    id: "67QWERTY",
    date: "2025-08-28",
    time: "03:15 PM",
    locations: {
      departure_point: "Toril, Davao City",
      destination: "Ulas, Davao City",
    },
    goods: {
      item: "Cement Bags",
      weight_in_kgs: "450",
    },
    truck_number: "DAV 1357",
  },
  {
    id: "91ZXCVBN",
    date: "2025-08-30",
    time: "06:00 AM",
    locations: {
      departure_point: "Matina, Davao City",
      destination: "Bangkal, Davao City",
    },
    goods: {
      item: "Aggregate",
      weight_in_kgs: "250",
    },
    truck_number: "YGV 4128",
  },
];

export const mockDrivers: Driver[] = [
  {
    id: "DRV-001",
    name: "Michael Rodriguez",
    profile_image:
      "https://images.unsplash.com/photo-1633332755192-727a05c4013d?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    email: "m.rodriguez@example.com",
    phone_number: "+63-555-0123",
    date_of_birth: "1985-03-15",
    license_number: "CDL123456789",
    license_expiry: "2025-12-31",
    license_type: "CDL-A",
    endorsements: ["HAZMAT", "Heavy Equipment", "Construction"],
    years_experience: 12,
    vehicle: {
      id: "VH-001",
      make: "Isuzu",
      model: "FVR",
      year: 2022,
      license_plate: "DVO-1234",
      vin: "1FUJA6CK18LAF1234",
      vehicle_type: "Dump Truck",
      capacity: {
        weight: 15000,
        volume: 8,
      },
      dimensions: {
        length: 8,
        width: 2.5,
        height: 3,
      },
      features: ["Hydraulic Dump", "GPS Tracking", "Backup Camera"],
      insurance: {
        policy_number: "INS-789456",
        expiry_date: "2024-12-15",
        coverage_amount: 1000000,
      },
    },
    ratings: {
      overall: 4.8,
      total_reviews: 147,
      breakdown: {
        punctuality: 4.9,
        communication: 4.7,
        safety: 4.8,
        professionalism: 4.8,
      },
      recent_reviews: [
        {
          id: "REV-001",
          rating: 5,
          comment: "Excellent service, delivered ahead of schedule!",
          reviewer_name: "John Smith",
          date: "2024-01-15",
          shipment_id: "SH-789456",
        },
      ],
    },
    location: {
      coordinates: {
        latitude: 7.0731,
        longitude: 125.6128,
      },
      area: "Puan",
      city: "Davao City",
      province: "Davao del Sur",
      state: "Philippines",
      country: "Philippines",
      zip_code: "8000",
      current_region: "Mindanao",
    },
    service_areas: ["Davao City", "Davao del Sur", "Davao del Norte"],
    preferred_routes: ["Puan to Matina", "Puan to Bangkal"],
    isAvailable: true,
    isOnline: true,
    availability_schedule: {
      days_available: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      hours_available: {
        start: "06:00",
        end: "20:00",
      },
    },
    current_status: "available",
    stats: {
      total_shipments: 234,
      on_time_deliveries: 228,
      successful_deliveries: 232,
      miles_driven: 450000,
      average_delivery_time: 18.5,
      acceptance_rate: 95,
    },
    documents: [
      {
        type: "license",
        url: "https://example.com/docs/license-001.pdf",
        expiry_date: "2025-12-31",
        verified: true,
      },
      {
        type: "insurance",
        url: "https://example.com/docs/insurance-001.pdf",
        expiry_date: "2024-12-15",
        verified: true,
      },
    ],
    background_check: {
      status: "approved",
      completed_at: "2023-06-15",
    },
    specializations: ["Construction Materials", "Heavy Loads", "Sand & Gravel"],
    languages: ["English", "Filipino", "Bisaya"],
    payment_methods: ["Bank Transfer", "GCash"],
    created_at: "2022-01-15T08:00:00Z",
    updated_at: "2024-01-20T14:30:00Z",
    last_online: "2024-01-20T14:25:00Z",
    last_delivery_date: "2024-01-19",
    badges: ["Top Rated", "Fast Responder", "Construction Expert"],
    membership_tier: "elite",
    referral_code: "MIKE-REF-001",
    contact_preferences: {
      sms_notifications: true,
      email_notifications: true,
      push_notifications: true,
    },
  },
  {
    id: "DRV-002",
    name: "Sarah Johnson",
    profile_image:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    email: "s.johnson@example.com",
    phone_number: "+63-555-0124",
    date_of_birth: "1990-08-22",
    license_number: "CDL987654321",
    license_expiry: "2024-11-30",
    license_type: "CDL-B",
    endorsements: ["Construction", "Heavy Equipment"],
    years_experience: 8,
    vehicle: {
      id: "VH-002",
      make: "Hino",
      model: "500 Series",
      year: 2021,
      license_plate: "TOR-5678",
      vin: "1FDXF86P1MEC98765",
      vehicle_type: "Dump Truck",
      capacity: {
        weight: 12000,
        volume: 6,
      },
      dimensions: {
        length: 7,
        width: 2.3,
        height: 2.8,
      },
      features: ["Hydraulic Dump", "Load Sensor", "GPS Tracking"],
      insurance: {
        policy_number: "INS-654321",
        expiry_date: "2024-10-20",
        coverage_amount: 750000,
      },
    },
    ratings: {
      overall: 4.6,
      total_reviews: 89,
      breakdown: {
        punctuality: 4.7,
        communication: 4.8,
        safety: 4.5,
        professionalism: 4.6,
      },
      recent_reviews: [
        {
          id: "REV-002",
          rating: 4,
          comment: "Good communication and careful handling",
          reviewer_name: "Lisa Brown",
          date: "2024-01-18",
          shipment_id: "SH-654321",
        },
      ],
    },
    location: {
      coordinates: {
        latitude: 7.0731,
        longitude: 125.6128,
      },
      area: "Toril",
      city: "Davao City",
      province: "Davao del Sur",
      state: "Philippines",
      country: "Philippines",
      zip_code: "8000",
      current_region: "Mindanao",
    },
    service_areas: ["Davao City", "Davao del Sur"],
    preferred_routes: ["Toril to Matina", "Toril to Puan"],
    isAvailable: false,
    isOnline: true,
    availability_schedule: {
      days_available: [
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "saturday",
      ],
      hours_available: {
        start: "07:00",
        end: "19:00",
      },
    },
    current_status: "on_delivery",
    estimated_availability_date: "2024-01-21T16:00:00Z",
    stats: {
      total_shipments: 156,
      on_time_deliveries: 148,
      successful_deliveries: 154,
      miles_driven: 220000,
      average_delivery_time: 12.3,
      acceptance_rate: 88,
    },
    documents: [
      {
        type: "license",
        url: "https://example.com/docs/license-002.pdf",
        expiry_date: "2024-11-30",
        verified: true,
      },
    ],
    background_check: {
      status: "approved",
      completed_at: "2023-05-10",
    },
    specializations: ["Construction Materials", "Sand Transport", "Quick Delivery"],
    languages: ["English", "Filipino"],
    payment_methods: ["Bank Transfer"],
    created_at: "2022-03-10T10:30:00Z",
    updated_at: "2024-01-20T15:45:00Z",
    last_online: "2024-01-20T15:40:00Z",
    last_delivery_date: "2024-01-18",
    badges: ["Careful Handler", "Local Specialist"],
    membership_tier: "premium",
    contact_preferences: {
      sms_notifications: false,
      email_notifications: true,
      push_notifications: true,
    },
  },
  {
    id: "DRV-003",
    name: "James Wilson",
    profile_image:
      "https://plus.unsplash.com/premium_photo-1677368597077-009727e906db?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    email: "j.wilson@example.com",
    phone_number: "+63-555-0125",
    date_of_birth: "1978-12-03",
    license_number: "CDL456789123",
    license_expiry: "2026-03-15",
    license_type: "CDL-A",
    endorsements: ["Heavy Equipment", "Construction Materials"],
    years_experience: 20,
    vehicle: {
      id: "VH-003",
      make: "Mitsubishi",
      model: "Fuso Fighter",
      year: 2023,
      license_plate: "MAT-9012",
      vin: "1XP5DB9X7YN789012",
      vehicle_type: "Dump Truck",
      capacity: {
        weight: 18000,
        volume: 10,
      },
      dimensions: {
        length: 9,
        width: 2.5,
        height: 3.2,
      },
      features: ["Advanced Hydraulics", "Load Monitor", "Safety Sensors"],
      insurance: {
        policy_number: "INS-123789",
        expiry_date: "2025-01-30",
        coverage_amount: 1500000,
      },
    },
    ratings: {
      overall: 4.9,
      total_reviews: 203,
      breakdown: {
        punctuality: 4.9,
        communication: 4.8,
        safety: 5.0,
        professionalism: 4.9,
      },
      recent_reviews: [
        {
          id: "REV-003",
          rating: 5,
          comment: "Most professional driver I've ever worked with!",
          reviewer_name: "Robert Taylor",
          date: "2024-01-17",
          shipment_id: "SH-123456",
        },
      ],
    },
    location: {
      coordinates: {
        latitude: 7.0731,
        longitude: 125.6128,
      },
      area: "Matina",
      city: "Davao City",
      province: "Davao del Sur",
      state: "Philippines",
      country: "Philippines",
      zip_code: "8000",
      current_region: "Mindanao",
    },
    service_areas: ["Davao City", "Davao del Sur", "Davao del Norte", "Davao Oriental"],
    preferred_routes: ["Matina to Bangkal", "Matina to Ulas"],
    isAvailable: false,
    isOnline: false,
    availability_schedule: {
      days_available: ["tuesday", "wednesday", "thursday", "friday", "sunday"],
      hours_available: {
        start: "08:00",
        end: "22:00",
      },
    },
    current_status: "off_duty",
    stats: {
      total_shipments: 456,
      on_time_deliveries: 449,
      successful_deliveries: 454,
      miles_driven: 980000,
      average_delivery_time: 20.1,
      acceptance_rate: 92,
    },
    documents: [
      {
        type: "license",
        url: "https://example.com/docs/license-003.pdf",
        expiry_date: "2026-03-15",
        verified: true,
      },
      {
        type: "medical_certificate",
        url: "https://example.com/docs/medical-003.pdf",
        expiry_date: "2025-06-30",
        verified: true,
      },
    ],
    background_check: {
      status: "approved",
      completed_at: "2023-07-20",
    },
    specializations: ["Heavy Materials", "Construction Sites", "Long Distance"],
    languages: ["English", "Filipino", "Bisaya"],
    payment_methods: ["Bank Transfer", "PayMaya"],
    created_at: "2021-11-20T09:15:00Z",
    updated_at: "2024-01-19T18:20:00Z",
    last_online: "2024-01-19T18:15:00Z",
    last_delivery_date: "2024-01-18",
    badges: ["Safety First", "Veteran Driver", "Reliable"],
    membership_tier: "elite",
    referral_code: "JAMES-REF-003",
    contact_preferences: {
      sms_notifications: true,
      email_notifications: false,
      push_notifications: true,
    },
  },
  {
    id: "DRV-004",
    name: "Emily Chen",
    profile_image:
      "https://images.unsplash.com/photo-1580518324671-c2f0833a3af3?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGhlYWRzaG90c3xlbnwwfHwwfHx8MA%3D%3D",
    email: "e.chen@example.com",
    phone_number: "+63-555-0126",
    date_of_birth: "1992-05-18",
    license_number: "NCDL789123456",
    license_expiry: "2025-08-20",
    license_type: "CDL-B",
    endorsements: ["Construction"],
    years_experience: 3,
    vehicle: {
      id: "VH-004",
      make: "Isuzu",
      model: "NPR",
      year: 2022,
      license_plate: "BAN-3456",
      vin: "WD3PE8CC7N5890123",
      vehicle_type: "Dump Truck",
      capacity: {
        weight: 8000,
        volume: 4,
      },
      dimensions: {
        length: 6,
        width: 2.2,
        height: 2.5,
      },
      features: ["Compact Design", "Easy Maneuver", "Backup Camera"],
      insurance: {
        policy_number: "INS-456123",
        expiry_date: "2024-09-15",
        coverage_amount: 500000,
      },
    },
    ratings: {
      overall: 4.3,
      total_reviews: 34,
      breakdown: {
        punctuality: 4.2,
        communication: 4.5,
        safety: 4.4,
        professionalism: 4.3,
      },
      recent_reviews: [
        {
          id: "REV-004",
          rating: 4,
          comment: "Friendly and efficient service",
          reviewer_name: "David Kim",
          date: "2024-01-16",
          shipment_id: "SH-789123",
        },
      ],
    },
    location: {
      coordinates: {
        latitude: 7.0731,
        longitude: 125.6128,
      },
      area: "Bangkal",
      city: "Davao City",
      province: "Davao del Sur",
      state: "Philippines",
      country: "Philippines",
      zip_code: "8000",
      current_region: "Mindanao",
    },
    service_areas: ["Davao City"],
    preferred_routes: ["Bangkal to Matina", "Bangkal to Puan"],
    isAvailable: false,
    isOnline: true,
    availability_schedule: {
      days_available: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      hours_available: {
        start: "09:00",
        end: "17:00",
      },
    },
    current_status: "break",
    estimated_availability_date: "2024-01-20T16:30:00Z",
    stats: {
      total_shipments: 67,
      on_time_deliveries: 61,
      successful_deliveries: 65,
      miles_driven: 45000,
      average_delivery_time: 4.2,
      acceptance_rate: 78,
    },
    documents: [
      {
        type: "license",
        url: "https://example.com/docs/license-004.pdf",
        expiry_date: "2025-08-20",
        verified: true,
      },
    ],
    background_check: {
      status: "approved",
      completed_at: "2023-08-05",
    },
    specializations: ["Small Loads", "Quick Delivery", "City Routes"],
    languages: ["English", "Filipino", "Mandarin"],
    payment_methods: ["Bank Transfer", "GCash"],
    created_at: "2023-02-15T14:20:00Z",
    updated_at: "2024-01-20T15:00:00Z",
    last_online: "2024-01-20T14:55:00Z",
    last_delivery_date: "2024-01-20",
    badges: ["Rising Star"],
    membership_tier: "basic",
    contact_preferences: {
      sms_notifications: true,
      email_notifications: true,
      push_notifications: false,
    },
  },
  {
    id: "DRV-005",
    name: "Carlos Martinez",
    profile_image:
      "https://images.unsplash.com/photo-1584999734482-0361aecad844?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cHJvZmlsZSUyMHBob3Rvc3xlbnwwfHwwfHx8MA%3D%3D",
    email: "c.martinez@example.com",
    phone_number: "+63-555-0127",
    date_of_birth: "1988-11-30",
    license_number: "CDL654321987",
    license_expiry: "2024-07-25",
    license_type: "CDL-A",
    endorsements: ["Heavy Equipment", "Construction Materials"],
    years_experience: 6,
    vehicle: {
      id: "VH-005",
      make: "UD Trucks",
      model: "Quon",
      year: 2020,
      license_plate: "ULA-7890",
      vin: "1XKWD49X1LJ345678",
      vehicle_type: "Dump Truck",
      capacity: {
        weight: 20000,
        volume: 12,
      },
      dimensions: {
        length: 10,
        width: 2.5,
        height: 3.5,
      },
      features: ["Heavy Duty Dump", "Load Monitoring", "Safety Systems"],
      insurance: {
        policy_number: "INS-987654",
        expiry_date: "2024-06-30",
        coverage_amount: 1200000,
      },
    },
    ratings: {
      overall: 4.7,
      total_reviews: 112,
      breakdown: {
        punctuality: 4.6,
        communication: 4.7,
        safety: 4.8,
        professionalism: 4.7,
      },
      recent_reviews: [
        {
          id: "REV-005",
          rating: 5,
          comment: "Perfect handling of our construction materials",
          reviewer_name: "Construction Co LLC",
          date: "2024-01-19",
          shipment_id: "SH-456789",
        },
      ],
    },
    location: {
      coordinates: {
        latitude: 7.0731,
        longitude: 125.6128,
      },
      area: "Ulas",
      city: "Davao City",
      province: "Davao del Sur",
      state: "Philippines",
      country: "Philippines",
      zip_code: "8000",
      current_region: "Mindanao",
    },
    service_areas: ["Davao City", "Davao del Sur", "Davao del Norte"],
    preferred_routes: ["Ulas to Toril", "Ulas to Matina"],
    isAvailable: true,
    isOnline: true,
    availability_schedule: {
      days_available: [
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
      ],
      hours_available: {
        start: "05:00",
        end: "21:00",
      },
    },
    current_status: "available",
    stats: {
      total_shipments: 178,
      on_time_deliveries: 170,
      successful_deliveries: 175,
      miles_driven: 320000,
      average_delivery_time: 22.5,
      acceptance_rate: 85,
    },
    documents: [
      {
        type: "license",
        url: "https://example.com/docs/license-005.pdf",
        expiry_date: "2024-07-25",
        verified: true,
      },
    ],
    background_check: {
      status: "approved",
      completed_at: "2023-08-10",
    },
    specializations: [
      "Heavy Construction Materials",
      "Large Capacity",
      "Heavy Equipment Transport",
    ],
    languages: ["English", "Spanish", "Filipino"],
    payment_methods: ["Bank Transfer", "GCash"],
    created_at: "2022-08-10T11:45:00Z",
    updated_at: "2024-01-18T16:30:00Z",
    last_online: "2024-01-18T16:25:00Z",
    last_delivery_date: "2024-01-17",
    badges: ["Heavy Load Specialist"],
    membership_tier: "premium",
    contact_preferences: {
      sms_notifications: false,
      email_notifications: true,
      push_notifications: true,
    },
  },
];